### ISSUE TITLE
Centos7下使用tomcat的shutdown.sh 关闭时报错，找不到类，但是在启动时正常。

### ISSUE THREAD

**Issue by lifw555** [ThinkpadNC5/MyPerf4J#13]
[root@test logs]# /usr/local/tomcat/bin/shutdown.sh 
Using CATALINA_BASE:   /usr/local/tomcat
Using CATALINA_HOME:   /usr/local/tomcat
Using CATALINA_TMPDIR: /usr/local/tomcat/temp
Using JRE_HOME:        /usr/local/jdk
Using CLASSPATH:       /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar
2018-08-23 13:37:16.436 [MyPerf4J] ERROR AbstractBootstrap.initPerfStatsProcessor()
java.lang.ClassNotFoundException: cn.myperf4j.ext.psp.DefaultLoggerProcessor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at cn.myperf4j.core.AbstractBootstrap.initPerfStatsProcessor(AbstractBootstrap.java:225)
	at cn.myperf4j.core.AbstractBootstrap.doInitial(AbstractBootstrap.java:78)
	at cn.myperf4j.core.AbstractBootstrap.initial(AbstractBootstrap.java:33)
	at cn.myperf4j.asm.PreMain.premain(PreMain.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
2018-08-23 13:37:16.482 [MyPerf4J] ERROR AbstractBootstrap initPerfStatsProcessor() FAILURE!!!
2018-08-23 13:37:16.482 [MyPerf4J] ERROR AbstractBootstrap doInitial() FAILURE!!!

**Comment by lifw555** [comment]
初步判断是javaagent启动时，还没有加载webapps/ROOT项目中lib，所以找不到lib引起的。

**Comment by ThinkpadNC5** [comment]
嗯，是的，具体原因是因为javagAgent启动时的类加载器是系统类加载器，而tomcat自带类加载器，系统类加载器无法加载webapps/ROOT目录下lib包；
可以把MyPerf4J-Extension.jar包打到MyPerf4J-ASM.jar包中即可暂时解决此问题

**Comment by ThinkpadNC5** [comment]
你好，MyPerf4J 2.0 取消通过SPI配置MetricsProccessor的方式，解决在Tomcat和SpringBoot下的类加载问题。
